global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['app:8080'] #Provide your ip and Do not give localhost as we are running the Prometheus in docker
      labels:
        application: app
